services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: alertmanager
      POSTGRES_USER: alertmanager
      POSTGRES_PASSWORD: alertmanager_password
    ports:
      - "5432:5432"
    networks:
      - alertmanager
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alertmanager -d alertmanager"]
      interval: 10s
      timeout: 5s
      retries: 5

  alertmanager-1:
    build:
      context: .
      dockerfile: Dockerfile.alertmanager
    platform: linux/amd64
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager-1.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-1-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.listen-address=0.0.0.0:9093'
      - '--storage.db.driver=postgres'
      - '--storage.db.dsn=postgresql://alertmanager:alertmanager_password@postgres:5432/alertmanager?sslmode=disable'
      - '--storage.db.sync-interval=30s'
      - '--storage.db.node-timeout=5m'
      - '--storage.db.max-open-conns=25'
      - '--storage.db.max-idle-conns=5'
    networks:
      - alertmanager
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  alertmanager-2:
    build:
      context: .
      dockerfile: Dockerfile.alertmanager
    platform: linux/amd64
    ports:
      - "9094:9093"
    volumes:
      - ./alertmanager-2.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-2-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.listen-address=0.0.0.0:9093'
      - '--storage.db.driver=postgres'
      - '--storage.db.dsn=postgresql://alertmanager:alertmanager_password@postgres:5432/alertmanager?sslmode=disable'
      - '--storage.db.sync-interval=30s'
      - '--storage.db.node-timeout=5m'
      - '--storage.db.max-open-conns=25'
      - '--storage.db.max-idle-conns=5'
    networks:
      - alertmanager
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  alertmanager-3:
    build:
      context: .
      dockerfile: Dockerfile.alertmanager
    platform: linux/amd64
    ports:
      - "9095:9093"
    volumes:
      - ./alertmanager-3.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-3-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.listen-address=0.0.0.0:9093'
      - '--storage.db.driver=postgres'
      - '--storage.db.dsn=postgresql://alertmanager:alertmanager_password@postgres:5432/alertmanager?sslmode=disable'
      - '--storage.db.sync-interval=30s'
      - '--storage.db.node-timeout=5m'
      - '--storage.db.max-open-conns=25'
      - '--storage.db.max-idle-conns=5'
    networks:
      - alertmanager
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  webhook-server:
    build:
      context: .
      dockerfile: Dockerfile.webhook
    platform: linux/amd64
    ports:
      - "5001:5001"
    networks:
      - alertmanager
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  alertmanager-1-data:
  alertmanager-2-data:
  alertmanager-3-data:

networks:
  alertmanager:
    driver: bridge
